/**
 * ConfluenceSoapService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.hasaki.wiki;

public interface ConfluenceSoapService extends java.rmi.Remote {
    public boolean isPluginInstalled(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemotePage updatePage(java.lang.String in0, com.hasaki.wiki.RemotePage in1, com.hasaki.wiki.RemotePageUpdateOptions in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException, com.hasaki.wiki.VersionMismatchException;
    public java.lang.String[] getPermissions(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSearchResult[] search(java.lang.String in0, java.lang.String in1, int in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSearchResult[] search(java.lang.String in0, java.lang.String in1, java.util.HashMap in2, int in3) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSpace getSpace(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteComment getComment(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteLabel[] getRelatedLabelsInSpace(java.lang.String in0, java.lang.String in1, java.lang.String in2, int in3) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSpace[] getSpacesContainingContentWithLabel(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSpace[] getSpacesWithLabel(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteLabel[] getLabelsByDetail(java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3, java.lang.String in4) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteServerInfo getServerInfo(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemotePageSummary[] getChildren(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean movePageToTopLevel(java.lang.String in0, long in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public java.lang.String login(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.AuthenticationFailedException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteConfluenceUser getUserByName(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteUser getUser(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public java.lang.String renderContent(java.lang.String in0, java.lang.String in1, long in2, java.lang.String in3, java.util.HashMap in4) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public java.lang.String renderContent(java.lang.String in0, java.lang.String in1, long in2, java.lang.String in3) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemotePage getPage(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemotePage getPage(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean isPluginEnabled(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean removeSpaceGroup(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSpaceGroup[] getSpaceGroups(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public java.lang.String[] getPermissionsForUser(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean isDarkFeatureEnabled(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean hasGroup(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteClusterInformation getClusterInformation(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteAttachment[] getAttachments(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteAttachment addAttachment(java.lang.String in0, com.hasaki.wiki.RemoteAttachment in1, byte[] in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteAttachment addAttachment(java.lang.String in0, long in1, com.hasaki.wiki.RemoteAttachment in2, byte[] in3) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean removeAttachment(java.lang.String in0, long in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteContentPermissionSet getContentPermissionSet(java.lang.String in0, long in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteContentPermissionSet[] getContentPermissionSets(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteComment[] getComments(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteComment addComment(java.lang.String in0, com.hasaki.wiki.RemoteComment in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean removeComment(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemotePageSummary[] getDescendents(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemotePageSummary[] getAncestors(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public void addUser(java.lang.String in0, com.hasaki.wiki.RemoteUser in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public void addUser(java.lang.String in0, com.hasaki.wiki.RemoteUser in1, java.lang.String in2, boolean in3) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean logout(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteConfluenceUser getUserByKey(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteAttachment getAttachment(java.lang.String in0, long in1, java.lang.String in2, int in3) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSpaceSummary[] getSpaces(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteLabel[] getRelatedLabels(java.lang.String in0, java.lang.String in1, int in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public java.lang.String getSpaceStatus(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemotePageSummary[] getPages(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public java.lang.String[] getGroups(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemotePermission[] getPagePermissions(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean setContentPermissions(java.lang.String in0, long in1, java.lang.String in2, com.hasaki.wiki.RemoteContentPermission[] in3) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteComment editComment(java.lang.String in0, com.hasaki.wiki.RemoteComment in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean moveAttachment(java.lang.String in0, long in1, java.lang.String in2, long in3, java.lang.String in4) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemotePageSummary[] getTopLevelPages(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public byte[] getAttachmentData(java.lang.String in0, long in1, java.lang.String in2, int in3) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean isWatchingPage(java.lang.String in0, long in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean isWatchingSpace(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteContentSummaries getTrashContents(java.lang.String in0, java.lang.String in1, int in2, int in3) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean emptyTrash(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean deactivateUser(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean reactivateUser(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean removeSpace(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean removeUser(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean renameUser(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean removeGroup(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean removeAllPermissionsForGroup(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteLabel[] getRecentlyUsedLabels(java.lang.String in0, int in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteLabel[] getRecentlyUsedLabelsInSpace(java.lang.String in0, java.lang.String in1, int in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteLabel[] getMostPopularLabels(java.lang.String in0, int in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteLabel[] getMostPopularLabelsInSpace(java.lang.String in0, java.lang.String in1, int in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean addGroup(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean addUserToGroup(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean installPlugin(java.lang.String in0, java.lang.String in1, byte[] in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSpaceGroup getSpaceGroup(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.AlreadyExistsException, com.hasaki.wiki.RemoteException;
    public boolean setSpaceStatus(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public java.lang.String exportSpace(java.lang.String in0, java.lang.String in1, java.lang.String in2, boolean in3) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public java.lang.String exportSpace(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean removeUserFromGroup(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean hasUser(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean setEnableWysiwyg(java.lang.String in0, boolean in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSpace addSpace(java.lang.String in0, com.hasaki.wiki.RemoteSpace in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.AlreadyExistsException, com.hasaki.wiki.RemoteException;
    public java.lang.String[] getUserGroups(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemotePageSummary getPageSummary(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemotePageSummary getPageSummary(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemotePageHistory[] getPageHistory(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean movePage(java.lang.String in0, long in1, long in2, java.lang.String in3) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean removePage(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemotePage storePage(java.lang.String in0, com.hasaki.wiki.RemotePage in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException, com.hasaki.wiki.VersionMismatchException;
    public boolean purgeFromTrash(java.lang.String in0, java.lang.String in1, long in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSpaceSummary[] getSpacesInGroup(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSpace addSpaceWithDefaultPermissions(java.lang.String in0, com.hasaki.wiki.RemoteSpace in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.AlreadyExistsException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSpace storeSpace(java.lang.String in0, com.hasaki.wiki.RemoteSpace in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSpaceGroup addSpaceGroup(java.lang.String in0, com.hasaki.wiki.RemoteSpaceGroup in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.AlreadyExistsException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSpace addPersonalSpaceWithDefaultPermissions(java.lang.String in0, com.hasaki.wiki.RemoteSpace in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.AlreadyExistsException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSpace addPersonalSpace(java.lang.String in0, com.hasaki.wiki.RemoteSpace in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.AlreadyExistsException, com.hasaki.wiki.RemoteException;
    public java.lang.String[] getSpaceLevelPermissions(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean addPermissionToSpace(java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean addGlobalPermissions(java.lang.String in0, java.lang.String[] in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean addGlobalPermission(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean addAnonymousUsePermission(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean addAnonymousViewUserProfilePermission(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean removeAnonymousViewUserProfilePermission(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean removeGlobalPermission(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean addPermissionsToSpace(java.lang.String in0, java.lang.String[] in1, java.lang.String in2, java.lang.String in3) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean removePermissionFromSpace(java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3) throws java.rmi.RemoteException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteBlogEntry getBlogEntryByDayAndTitle(java.lang.String in0, java.lang.String in1, int in2, java.lang.String in3) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean editUser(java.lang.String in0, com.hasaki.wiki.RemoteUser in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean isActiveUser(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public java.lang.String[] getActiveUsers(java.lang.String in0, boolean in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean changeMyPassword(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean changeUserPassword(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean setUserInformation(java.lang.String in0, com.hasaki.wiki.RemoteUserInformation in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteUserInformation getUserInformation(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean setUserPreferenceBoolean(java.lang.String in0, java.lang.String in1, java.lang.String in2, boolean in3) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean getUserPreferenceBoolean(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean setUserPreferenceLong(java.lang.String in0, java.lang.String in1, java.lang.String in2, long in3) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public long getUserPreferenceLong(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean setUserPreferenceString(java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public java.lang.String getUserPreferenceString(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean addProfilePicture(java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3, byte[] in4) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean watchPage(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean watchPageForUser(java.lang.String in0, long in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean watchSpace(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean removePageWatch(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean removeSpaceWatch(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean removePageWatchForUser(java.lang.String in0, long in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteUser[] getWatchersForPage(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean isWatchingSpaceForType(java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteUser[] getWatchersForSpace(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public java.lang.String[] renameUsers(java.lang.String in0, java.util.HashMap in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteBlogEntry getBlogEntryByDateAndTitle(java.lang.String in0, java.lang.String in1, int in2, int in3, int in4, java.lang.String in5) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteBlogEntry getBlogEntry(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteBlogEntrySummary[] getBlogEntries(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteBlogEntry storeBlogEntry(java.lang.String in0, com.hasaki.wiki.RemoteBlogEntry in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException, com.hasaki.wiki.VersionMismatchException;
    public java.lang.String exportSite(java.lang.String in0, boolean in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public java.lang.String performBackup(java.lang.String in0, boolean in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean flushIndexQueue(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean clearIndexQueue(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteNodeStatus[] getClusterNodeStatuses(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean importSpace(java.lang.String in0, byte[] in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean setEnableAnonymousAccess(java.lang.String in0, boolean in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteLabel[] getLabelsById(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSearchResult[] getLabelContentById(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSearchResult[] getLabelContentByName(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public com.hasaki.wiki.RemoteSearchResult[] getLabelContentByObject(java.lang.String in0, com.hasaki.wiki.RemoteLabel in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.RemoteException;
    public boolean removeAnonymousUsePermission(java.lang.String in0) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean addAnonymousPermissionToSpace(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean addAnonymousPermissionsToSpace(java.lang.String in0, java.lang.String[] in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean removeAnonymousPermissionFromSpace(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public java.lang.String convertWikiToStorageFormat(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.hasaki.wiki.RemoteException;
    public boolean removePageVersionById(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean removePageVersionByVersion(java.lang.String in0, long in1, int in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean addLabelByName(java.lang.String in0, java.lang.String in1, long in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean addLabelById(java.lang.String in0, long in1, long in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean addLabelByObject(java.lang.String in0, com.hasaki.wiki.RemoteLabel in1, long in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean addLabelByNameToSpace(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean removeLabelByName(java.lang.String in0, java.lang.String in1, long in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean removeLabelById(java.lang.String in0, long in1, long in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean removeLabelByObject(java.lang.String in0, com.hasaki.wiki.RemoteLabel in1, long in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
    public boolean removeLabelByNameFromSpace(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.hasaki.wiki.InvalidSessionException, com.hasaki.wiki.NotPermittedException, com.hasaki.wiki.RemoteException;
}
